---
title: "<center><div class='mytitle'>Awesome Geodata Table</div></center>"
subtitle: "<center><div class='mytitle'>A searchable collection of geodatasets maintained by its community</div></center>"
# author: "Anne-Karin Cooke, Sandra Willkommen, Mariana Espina-Gomez, Max Nölscher"
date: "<center><div class='mydate'>`r format(Sys.time(), '%d %B, %Y')`</div></center>"
output:
  html_document:
      css: style.css
      toc: FALSE
      includes: 
        before_body: header.html
---

<!-- <br> -->

```{r setup, include=FALSE}
library(readr)
library(dplyr)
library(DT)
knitr::opts_chunk$set(echo = TRUE)
source("R/awesome_geodata_table_html.R")
```

```{r, include=FALSE}
awesome_geodata_table_raw <- read_csv2( "inst/extdata/awesome_geodata_table.csv",
                                        col_types = "fffffffffffficcffffffff")
awesome_geodata_table_raw <- awesome_geodata_table_raw |>
  dplyr::slice(-c(1, 2))
```

```{r, echo=FALSE}
awesome_geodata_table_raw |> 
  awesome_geodata_table_html()
```

