---
title: "R Notebook"
output: html_notebook
---

The [R plugin](https://www.jetbrains.com/help/pycharm/r-plugin-support.html) for IntelliJ-based IDEs provides
handy capabilities to work with the [R Markdown](https://www.jetbrains.com/help/pycharm/r-markdown.html) files.
To [add](https://www.jetbrains.com/help/pycharm/r-markdown.html#add-code-chunk) a new R chunk,
position the caret at any line or the code chunk, then click "+".

```{r}
library(reactable)


```


```{r}
library(reactable)
library(dplyr)
tibble(
  a1 = as.Date(1:3, origin = "2020-02-02"),
  a2 = 1:3,
  b = 1:3,
  c1 = c("\\[ \\frac{m}{s} \\]", "$$\\frac{kg}{m^3}$$", "$$kg m**-3$$"),
  c2 = 1:3,
  c3 = 1:3,
)|> reactable(
  columnGroups = list(
    colGroup(name = "a", columns = c("a1", "a2")),
    colGroup(name = "c", columns = c("c1", "c2", "c3"))),
  defaultColDef = colDef(
          cell = function(value) format(value, nsmall = 1),
          headerStyle = list(display = "flex", justifyContent = "center")
        ),
  filterable = TRUE,
  searchable = TRUE)

```
